###注册
POST http://localhost:8080/api/account/register
Content-Type: application/json

{
  "username": "ww",
  "password": "123123",
  "nickname": "ww"
}
###
POST http://localhost:8080/api/account/register
Content-Type: application/json

{
  "username": "zzx12345455",
  "password": "zxzx12qwe",
  "nickname": "sd"
}
###
POST http://localhost:8080/api/account/register
Content-Type: application/json

{
  "username": "sddvfdos123",
  "password": "sadvdfosdf3",
  "nickname": "addvdfosf3"
}
###
POST http://localhost:8080/api/account/register
Content-Type: application/json

{
  "username": "cc",
  "password": "123123",
  "nickname": "cc"
}
###

###登录
POST http://localhost:8080/api/account/login
Content-Type: application/json

{
  "username": "1",
  "password": "123123"
}
###


###登出
POST http://localhost:8080/api/account/logout
Content-Type: application/json
###



###注销
DELETE http://localhost:8080/api/account/3
Content-Type: application/json
###

###查询是否有重复姓名
GET http://localhost:8080/api/account/username?username=Olalala
Accept: application/json
###

###查询是否有重复昵称
GET http://localhost:8080/api/account/nickname?nickname=aasdas
Accept: application/json

###



###随机获取用户
GET http://localhost:8080/api/account/show?num=4
Accept: application/json

###

###获取所有用户
GET http://localhost:8080/api/account/all?pageSize=4&pageNum=2
Accept: application/json
###
