#先登录
POST http://localhost:8081/api/account/login
Content-Type: application/json

{
  "username": "1",
  "password": "123123"
}
###



#关注
POST http://localhost:8081/api/follow/11
Content-Type: application/json

{}

###

#获取关注列表
GET http://localhost:8081/api/follow?pageSize=4&pageNum=2
Accept: application/json

###

#取消关注
DELETE http://localhost:8081/api/follow/11
Accept: application/json

###
